language: node_js
node_js:
- '0.11'
- '0.10'
services:
- couchdb
script:
- se-interpreter selenium/interpreter_config.json
env:
  global:
  - SAUCE_USERNAME=franhub
  - secure: jkq9Do0q2W4Q8Kp3zhqVEQyDeqvk+8kNDjNC0t5tpbVP8thiNHGDojiAUgIwhJT5lV6m0RtAKjiCqztlZA1tfLd488tkJbW5ur2ENm7HhuHFP7m22vurrezLiAHSCL0EcmvbqI0hbkabOBv05oo2A8vJb3Mo/vrY0RcbIst/j9k=
